
stages:          
  - preview

preview-page:
  stage: preview
  script:
    - nix build --extra-experimental-features nix-command --extra-experimental-features flakes .#default
    - cp -r result derefresult
    - nix-shell -p zip --command "zip -r website.zip derefresult"
  artifacts:
    name: "website-${CI_COMMIT_REF_NAME}"
    when: always
    paths:
      - website.zip


